import { defineStore } from 'pinia'

import { FORKS, useAuth } from '~/auth'
import { useForkSync } from '~/forksync'
import { openPullRequest } from '~/github'
import { withBase } from '~/paths'
import { useStore } from '~/store'

/** What a run built, as the run itself wrote it. */
export interface HistoryBundle {
  runAt: string
  sources: Record<string, unknown>
  /** File name -> the whole file, exactly as it should be committed. */
  files: Record<string, string>
}

/** Published alongside the per-type files: which reference designators exist. */
export const REFDES_FILE = 'refDesList.csv'

/** Rows in a file, not counting its header. The run writes a trailing newline,
 *  which would otherwise count as a deployment. */
export function rowCount(text: string) {
  return Math.max(text.split('\n').filter((line) => line.trim()).length - 1, 0)
}

/**
 * The history belonging to the run being read.
 *
 * Published runs are named `report_<stamp>` and their histories
 * `history_<stamp>`, so one follows from the other rather than being looked up.
 * A null name is the current run, whose history is at the fixed url.
 */
export function historyUrlFor(latest: string, name: string | null) {
  if (!name) return latest
  return latest.replace(/[^/]+$/, name.replace('report_', 'history_'))
}

/**
 * Proposing the published deployment history to the reviewer's fork.
 *
 * This is a product rather than a finding: one csv per instrument type saying
 * what was where and when, with the calibration that was in force for each
 * deployment. The run builds it -- it already holds the deployment sheets and
 * both calibration indexes -- and publishes it beside the report, so nothing
 * here regenerates it. A reviewer commits exactly the bytes the run wrote.
 *
 * Fetched only when this page is opened. It is a couple of hundred kilobytes
 * that every other page would otherwise carry.
 */
export const useDeployHistory = defineStore('deployHistory', () => {
  const bundle = ref<HistoryBundle | null>(null)
  const status = ref<'idle' | 'loading' | 'ready' | 'error'>('idle')
  const error = ref('')
  const submitting = ref(false)
  const result = ref<{ url: string | null; message: string } | null>(null)

  const sync = useForkSync()
  const definition = FORKS.find((each) => each.key === 'deployments')!

  function urlFor(name: string | null) {
    const config = useRuntimeConfig()
    return historyUrlFor(withBase(config.app.baseURL, config.public.historyUrl as string), name)
  }

  /** Which load is the latest, so a run picked and then another does not land
   *  the first one's history under the second one's stamp. */
  let sequence = 0

  async function load() {
    const mine = ++sequence
    status.value = 'loading'
    error.value = ''
    // A pull request opened for the previous run's history is not this one's.
    result.value = null
    try {
      const fetched = await $fetch<HistoryBundle>(urlFor(useStore().selected))
      if (mine !== sequence) return
      if (!fetched || typeof fetched !== 'object' || !fetched.files) {
        throw new Error('That run published no deployment history.')
      }
      bundle.value = fetched
      status.value = 'ready'
    } catch (caught) {
      if (mine !== sequence) return
      error.value = caught instanceof Error ? caught.message : String(caught)
      status.value = 'error'
    }
  }

  const files = computed(() =>
    Object.entries(bundle.value?.files ?? {})
      .map(([name, text]) => ({ name, text, rows: rowCount(text) }))
      .sort((a, b) => a.name.localeCompare(b.name)))

  const deployments = computed(() =>
    files.value.filter((file) => file.name !== REFDES_FILE)
      .reduce((total, file) => total + file.rows, 0))

  /**
   * One pull request carrying the whole history, on the reviewer's own fork.
   *
   * Every file at once, because the history is one product: half of it against
   * one run and half against another would be a repository that never described
   * any single state of the deployment sheets. Files the repository holds that
   * the history does not name -- `NODE_deployments.csv` -- are left alone,
   * because the commit is built on the fork's own tree.
   */
  async function propose() {
    if (!bundle.value) return
    const auth = useAuth()
    submitting.value = true
    result.value = null
    try {
      const blocked = await sync.check('deployments', true)
      if (blocked) throw new Error(blocked)
      const fork = auth.forkFor('deployments')
      const built = new Date(bundle.value.runAt).toISOString().slice(0, 10)
      const url = await openPullRequest(
        fork, definition.base, bundle.value.files,
        `Deployment history, ${built}`,
        [
          `${deployments.value} deployments across ${files.value.length - 1} instrument types,`,
          `regenerated by the verification run of ${new Date(bundle.value.runAt).toISOString()}.`,
          '',
          'Built from the asset-management deployment sheets and the calibration files in both',
          'repositories. Each row names the calibration that was in force at that deployment.',
          '',
          `Proposed from the metadata dashboard by ${auth.initials} (${auth.user?.login}).`,
          '',
          'Files this repository holds that the history does not name are untouched.',
          'Review it here, then raise the pull request to the upstream repository by hand.',
        ].join('\n'),
        'history',
      )
      result.value = url
        ? { url, message: 'Pull request opened on your deployments fork.' }
        : { url: null, message: 'Your fork already matches this history — nothing to propose.' }
    } catch (caught) {
      result.value = {
        url: null,
        message: caught instanceof Error ? caught.message : String(caught),
      }
    } finally {
      submitting.value = false
    }
  }

  return { bundle, status, error, files, deployments, submitting, result, load, propose }
})
